### ISSUE TITLE
Getting error rendering sample apps in Windows 10 enviroment (i.e. ch4/ng-for/detailed)

### ISSUE THREAD

**Issue by MAJLGC** [mgechev/switching-to-angular2#10]
![ch4_ng-for_detailed-syntax_error](https://cloud.githubusercontent.com/assets/3033029/15992629/d1834e96-30d0-11e6-829b-7d79fe01db09.jpg)

**Comment by mgechev** [comment]
Did you make any changes in the directory? Can you reproduce it with clean clone of the repository?

**Comment by MAJLGC** [comment]
I did no changes in the directory.
I`ve erased my local repo and cloned again the project gihthub repo following your  suggested commands. Sorry, but the error still remains

**Comment by MAJLGC** [comment]
All examples are rendering, exept following ones:
Chapter 4, List of items (detailed syntax)
Chapter 4, List of items (syntax sugar)
Chapter 4, Basic todo application

**Comment by mgechev** [comment]
Thanks for the issue! I'm working on updating all the examples to RC here https://github.com/mgechev/switching-to-angular2/pull/7. I'll incorporate a fix for your issue as well.
