### ISSUE TITLE
Please Help with upgrading ControlErrors component to use REACTIVE_FORM_DIRECTIVES

### ISSUE THREAD

**Issue by ckapilla** [mgechev/switching-to-angular2#11]
I've been trying to update the Control Errors component to use the REACTIVE_FORM_DIRECTIVES, but I can't get past the constructor:
  constructor(@Host() private formDir: NgFormModel) {}
I can't figure out what to pass in in place of **NgFormModel**...**FormGroup** is not a provider, and **FormGroupDirective** gets passed in as null.
Hope you can help!
thanks

**Comment by mgechev** [comment]
Hey @ckapilla! The new forms module is not part of the first edition of the book "Switching to Angular 2". However, [angular2-seed](https://github.com/mgechev/angular2-seed) uses all the newest APIs provided by Angular 2. This means that you can experiment with it and use the [gitter](https://gitter.im/mgechev/angular2-seed) if you have any questions.
