### ISSUE TITLE
compatibility issues - ng2-rc5

### ISSUE THREAD

**Issue by kukoman** [mgechev/switching-to-angular2#12]
Hi Minko,

It seems the latest rc5 introduced some braking changes. I just checked ch4/es5/tabs and it throws a bunch of errors.

```
Unhandled Promise rejection: Template parse errors:
No provider for constructor ("<tabs>
  [ERROR ->]<tab tabTitle="First">First tab content</tab>
```

**Comment by kukoman** [comment]
talking rubbish here :) it's not working in the latest vivaldi on linux... sorry to bother your, works fine in FF

**Comment by mgechev** [comment]
@kukoman no worries. We're considering to introduce RC.5 in a second edition of the book. Unfortunately, at this point there are too many changes in order to be able to painlessly update the book's content.
