### ISSUE TITLE
Unable to compile TypeScript   gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)

### ISSUE THREAD

**Issue by uixdk** [mgechev/switching-to-angular2#14]
$ sudo npm run start

> angular2-seed@0.0.0 start /Users/panduozhi/code/myproj/angulr/ng2/switching-to-angular2
> gulp serve --env dev
## [11:49:36] Requiring external module ts-node/register

⨯ Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
manual_typings/merge-stream.d.ts (2,36): Cannot find namespace 'NodeJS'. (2503)
manual_typings/merge-stream.d.ts (3,33): Cannot find namespace 'NodeJS'. (2503)
manual_typings/merge-stream.d.ts (4,17): Cannot find namespace 'NodeJS'. (2503)
manual_typings/systemjs-builder.d.ts (4,60): Cannot find name 'Promise'. (2304)
manual_typings/systemjs-builder.d.ts (5,65): Cannot find name 'Promise'. (2304)
tools/config.ts (1,28): Cannot find module 'fs'. (2307)
tools/config.ts (2,31): Cannot find module 'path'. (2307)
tools/config.ts (11,52): Cannot find name '__dirname'. (2304)
tools/config.ts (59,25): Cannot find name 'require'. (2304)
tools/utils.ts (5,23): Cannot find module 'path'. (2307)
tools/utils.ts (10,19): Cannot find name '__dirname'. (2304)
tools/utils.ts (17,17): Cannot find name 'require'. (2304)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/panduozhi/code/myproj/angulr/ng2/switching-to-angular2/npm-debug.log

**Comment by mgechev** [comment]
Using `sudo` most likely creates the problem. You can take a look at [this article here](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by zion223** [comment]
I have the same question .Can you resolve it?

**Comment by justforuse** [comment]
@Jayruiping
We should `typings install` first, and those problem solved.

maybe you should edit typings.json first: convert `ambientDependencies` to `globalDependencies`
