### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by svet007** [mgechev/switching-to-angular2#16]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.0.0-rc.6 wants rxjs@5.0.0-beta.11
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.6 wants rxjs@5.0.0-beta.11

[npm-debug.log.zip](https://github.com/mgechev/switching-to-angular2/files/450949/npm-debug.log.zip)

**Comment by mgechev** [comment]
Haven't locked the dependencies. The issue should be fixed now.

**Comment by svet007** [comment]
Works now! Thanks a lot for a very quick fix!
