### ISSUE TITLE
More TAB, similar to the browser tabs, each TAB when a separate form

### ISSUE THREAD

**Issue by smile2014** [mgechev/switching-to-angular2#18]
Hello,mgechev,can you help me, I want to do a click on the menu, add a new TAB, rather than as it is now click menu routing switch, the middle area is changed, how to implement

**Comment by mgechev** [comment]
The code samples and this repository are related to the book. For getting a better idea how Angular works I'd recommend you to go through the next chapters and take a look at the Angular docs on https://angular.io.
