### ISSUE TITLE
Using Cloud 9 Workspace - Script references for ch4/ee5/HelloWorld/index.html not found 

### ISSUE THREAD

**Issue by bofcarbon1** [mgechev/switching-to-angular2#19]
I'm working in a Cloud 9 Workspace and have installed node.js, npm and Typescript. Its bad enough that we have the 'ts' folders in one place and that they get compiled to JavaScript that in no way resembles Typescript. The book is not clear that we have a complete 'HelloWorld' app to test under 'ee5'. 

All of the script references to 'unpkg.com' are not found when the 'index.html' page is launched in Google Chrome. 

start snippet from Google Chrome web tools .....

Failed to load resource: the server responded with a status of 404 ()
core.umd.js:5977 Uncaught TypeError: Cannot read property 'Subject' of undefined(…)
unpkg.com/@angular/common@2.1.2/bundles/common.umd.js:111 Uncaught TypeError: _angular_core.OpaqueToken is not a constructor(…)
unpkg.com/@angular/compiler@2.1.2/bundles/compiler.umd.js:6152 Uncaught TypeError: Cannot read property 'isDefaultChangeDetectionStrategy' of undefined(…)
unpkg.com/@angular/platform-browser@2.1.2/bundles/platform-browser.umd.js:12 Uncaught TypeError: Cannot read property 'DebugDomRootRenderer' of undefined(…)
unpkg.com/@angular/platform-browser-dynamic@2.1.2/bundles/platform-browser-dynamic.umd.js:12 Uncaught TypeError: Cannot read property 'INTERNAL_BROWSER_PLATFORM_PROVIDERS' of undefined(…)
app.js:1 Uncaught TypeError: ng.core.Component is not a function(…)

end snippet.....

Are we supposed to go to 'unpkg.com' and follow their instructions to get the associated script files recognized, found and loaded at run time?

That's a huge assumption to make if so.   My first problem with this book is that you make leaps and assumptions for preparation of the environment to code and test our dependency on Typescript, npm, node.js and more.   I learned Angular 1 using MVC and .NET in Visual Studio. All I had to do was get the Angular Scripts. 

Why are all you people who plug node.js and Typescript avoiding detailed setup for the environment to access the script library dependencies?  On top of that you should use a neutral approach and not assume that the work is being done on a local machine. Cloud services like Cloud 9 build in features that allow the use of npm. Any configuration for environment setup should be in user generated files. The ones that configure for items under an app.   It amazing how much time is spent getting past being able to reference a script file that should only take 2 minutes add to a bundle file that gets loaded using a few lines of bundle references in a layout or master or main view.  But I can't see this concept in node at all.  If we set up core angular libraries in our TypeScript file then why do we have external references to Angular scripts in the JavaScript file and what's the point of importing references and having JavaScript compiled code that has warning messages about not being able to find 'ng.core...'.  

Shouldn't all of these script dependent files be in our 'node_module' folder and shouldn't that be were we pick up our run time Angular scripts?

**Comment by mgechev** [comment]
Hey @bofcarbon1, thanks for giving the project a try!

Some of the script references were incorrect. I fixed them here https://github.com/mgechev/switching-to-angular2/commit/e1edd30a2bd7d90f63b58753feffc293a60fa98d. You can clone the latest master and try again.

> My first problem with this book is that you make leaps and assumptions for preparation of the environment to code and test our dependency on Typescript, npm, node.js and more. I learned Angular 1 using MVC and .NET in Visual Studio. All I had to do was get the Angular Scripts.

Node, TypeScript are requirement for learning how to build Angular applications with TypeScript. We're not forcing the readers to install all these dependencies on their local machines, if they prefer to use Cloud IDE it is ok as soon as they know how to configure it.

Thanks for pointing out the incorrect links again!

**Comment by bofcarbon1** [comment]
Minko,

Hey thanks for the rapid response and sorry for the rant.
The rant is pretty much my learning curve and frustration.
I should be used to it now having gone from COBOL mainframe,
to Java to .NET object oriented coding then to JavaScript, JQuery,
Ajax and Json.   The MEAN stack is a new challenge. Lots of
changes all at once 'BOOM'!

The GitHub link with the modifications worked perfectly.
When reloaded the 'Hello World' content loaded and displayed.
Honestly could not see how the 'target' string in the 'App' class
was going to be inserted in the <app></app> tag. I was still thinking
'ngrouter' and routing would be swapping out partial view content.
I never used templates though in Angular 1 and I think I'll have to
get used to them now.

I'll get there. Dinosaurs just move a little slower.

Thanks,
Brian

**Comment by mgechev** [comment]
Yes...I agree the tooling overhead is huge and I understand your frustration. Working on angular-seed since Angular 2 alpha.14 I went through almost all changes...

For a modern Angular application you'll need at least:
- Node.js
- TypeScript Compiler
- Angular template compiler (for AoT compilation)
- Minifier
- bundler (rollup.js, google closure compiler or webpack...)
- Angular mobile toolkit for Service Workers management
- Module loader
- ...

That's why I recommend using starters such as [angular-seed](https://github.com/mgechev/angular-seed) or [angular-cli](https://github.com/angular/angular-cli). Both provide solid base with all the boilerplates handled.
