### ISSUE TITLE
Multiple errors with clean checkout

### ISSUE THREAD

**Issue by ctriou** [mgechev/switching-to-angular2#22]
After performing a clean clone of the project, running "npm install && npm start", I cannot get past console errors in my browser. I've tried with a few of the files in ch4. Right now I'm trying /ch4/es5/tabs/index.html.

First I was getting an HTTP 404 on https://unpkg.com/rxjs@5.0.0-rc.4/bundles/Rx.umd.js. so I changed it to Rx.js to get past this. 

Then I receive:

`Uncaught TypeError: ng.platformBrowserDynamic.bootstrap is not a function(…)`

It looks like the index.html files throughout the examples need to be updated to match the same versions of the libraries as the package.json file. For instance, if I change /ch4/es5/hello-world/index.html to:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <app></app>
  <script src="https://unpkg.com/zone.js@0.6.12/dist/zone.js"></script>
  <script src="https://unpkg.com/reflect-metadata@0.1.3/Reflect.js"></script>
  <script src="https://unpkg.com/rxjs@5.0.0-beta.6/bundles/Rx.umd.js"></script>
  <script src="https://unpkg.com/@angular/core@2.0.0-rc.4/bundles/core.umd.js"></script>
  <script src="https://unpkg.com/@angular/common@2.0.0-rc.4/bundles/common.umd.js"></script>
  <script src="https://unpkg.com/@angular/compiler@2.0.0-rc.4/bundles/compiler.umd.js"></script>
  <script src="https://unpkg.com/@angular/platform-browser@2.0.0-rc.4/bundles/platform-browser.umd.js"></script>
  <script src="https://unpkg.com/@angular/platform-browser-dynamic@2.0.0-rc.4/bundles/platform-browser-dynamic.umd.js"></script>
  <script src="./app.js"></script>
</body>
</html>
```

It then seems to fix the problem.

Thanks for the help. I'm enjoying the book so far.

**Comment by mgechev** [comment]
Sorry for the inconvenience. I suppose I've pushed changes from final to the master branch by mistake. I'll fix this later tonight.

**Comment by mgechev** [comment]
The links were without fixed versions. It should be fine now. For the latest version of the examples which use `NgModule` you can take a look at [final](https://github.com/mgechev/switching-to-angular2/tree/final) branch.
