### ISSUE TITLE
run problems--when i excute npm install for switching-to-angular2

### ISSUE THREAD

**Issue by BillCindy** [mgechev/switching-to-angular2#24]
Installing strip-ansi@^3.0.1platform unsupported gulp-watch@4.3.11 › chokidar@1.6.1 › fsevents@1.0.15 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
Downloading https://npm.taobao.org/mirrors/phantomjs2.0.0-20141016-x86/phantomjs-2.0.0-20141016-win-x86.zip
Saving to C:\Users\bill\AppData\Local\Temp\phantomjs\phantomjs-2.0.0-20141016-win-x86.zip
Receiving...

Error requesting archive.
Status: 404
Request options: {
  "uri": "https://npm.taobao.org/mirrors/phantomjs2.0.0-20141016-x86/phantomjs-2.0.0-20141016-win-x86.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "date": "Mon, 26 Dec 2016 23:57:38 GMT",
  "content-type": "text/plain; charset=utf-8",
  "content-length": "9",
  "connection": "close",
  "vary": "Accept-Encoding",
  "x-response-time": "0"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node install.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\bill\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.13.3
npminstall args: D:\Program Files (x86)\Node\node.exe C:\Users\bill\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\bill\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

**Comment by mgechev** [comment]
I'll drop phantomjs since it's not required to be part of the code for the book.

**Comment by mgechev** [comment]
Actually the dependencies are now updated and phantomjs, together with karma are dropped. The issue should has been fixed.

**Comment by BillCindy** [comment]
thanks! it's very kind of you !
