### ISSUE TITLE
Two file compilation failed and report error

### ISSUE THREAD

**Issue by zngong** [mgechev/switching-to-angular2#25]
the files name is gulp.ts and utils.ts

**Comment by mgechev** [comment]
Can you give me more details? `gulpfile.ts` and `utils.ts` are not supposed to be compiled at all, since as part of the build process we're using `ts-node` which automatically executes the build-related files.

**Comment by 0415fh** [comment]
Cannot find module 'internal/fs'


npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Swallow/Desktop/switching-to-angular2/npm-debug.log

**Comment by mgechev** [comment]
@0415fh https://github.com/nodejs/node/issues/9377
