### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jroelens72** [mgechev/switching-to-angular2#27]
>npm ls -g
--empty
>npm --version
3.10.10

Windows 7

//after cloning:
>cd switching-to-angular2
>npm install
npm WARN deprecated gulp-tslint-stylish@1.1.1: Replaced by core tslint formatter
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it
 the tree.

> angular2-seed@0.0.0 postinstall C:\Users\xxxx\AngularJS2\switching-to-angular2
> rimraf typings && typings install && gulp check.versions && gulp postinstall

└── (No dependencies)

[15:12:18] Requiring external module ts-node/register
----------------------------------
? Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
manual_typings\merge-stream.d.ts (2,36): Cannot find namespace 'NodeJS'. (2503)
manual_typings\merge-stream.d.ts (3,33): Cannot find namespace 'NodeJS'. (2503)
manual_typings\merge-stream.d.ts (4,17): Cannot find namespace 'NodeJS'. (2503)
manual_typings\systemjs-builder.d.ts (4,60): Cannot find name 'Promise'. (2304)
manual_typings\systemjs-builder.d.ts (5,65): Cannot find name 'Promise'. (2304)
tools\config.ts (1,28): Cannot find module 'fs'. (2307)
tools\config.ts (2,31): Cannot find module 'path'. (2307)
tools\config.ts (11,52): Cannot find name '__dirname'. (2304)
tools\config.ts (59,25): Cannot find name 'require'. (2304)
tools\utils.ts (5,23): Cannot find module 'path'. (2307)
tools\utils.ts (10,19): Cannot find name '__dirname'. (2304)
tools\utils.ts (17,17): Cannot find name 'require'. (2304)
tools\utils\server.ts (2,26): Cannot find module 'express'. (2307)
tools\utils\server.ts (5,30): Cannot find module 'serve-static'. (2307)
tools\utils\server.ts (6,23): Cannot find module 'path'. (2307)
tools\utils\server.ts (19,20): Cannot find name 'process'. (2304)
tools\utils\server.ts (39,25): Cannot find name 'process'. (2304)
tools\utils\tasks_tools.ts (1,23): Cannot find module 'gulp'. (2307)
tools\utils\tasks_tools.ts (2,23): Cannot find module 'gulp-util'. (2307)
tools\utils\tasks_tools.ts (3,24): Cannot find module 'chalk'. (2307)
tools\utils\tasks_tools.ts (6,50): Cannot find module 'fs'. (2307)
tools\utils\tasks_tools.ts (7,20): Cannot find module 'path'. (2307)
tools\utils\tasks_tools.ts (19,10): Cannot find name 'require'. (2304)
tools\utils\template_injectables.ts (2,20): Cannot find module 'path'. (2307)
tools\utils\template_locals.ts (2,21): Cannot find module 'fs'. (2307)
tools\utils\template_locals.ts (3,34): Cannot find module 'path'. (2307)
tools\utils\template_locals.ts (71,19): Cannot find name '__dirname'. (2304)
----------------------------------

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `rimraf typings && typings install && gulp check.versions && gulp postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'rimraf typings && typings install && gulp check.versions && gulp postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf typings && typings install && gulp check.versions && gulp postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxxx\AngularJS2\switching-to-angular2\npm-debug.log

**Comment by yckjz** [comment]
me too!

**Comment by 404157386** [comment]
Same as here, please help...

**Comment by 404157386** [comment]
I found that it always hit error when run gulp, why?
If i run command such as 'gulp test' in this path, hit the same error.
Is the _manual_typings/merge-stream.d.ts_ wrong? 
Why cannot find namespace 'NodeJs'?
Please help...

<img width="570" alt="qq20170218-085726 2x" src="https://cloud.githubusercontent.com/assets/16297662/23088540/4ea80b12-f5b8-11e6-950f-d81eaf9a3e91.png">

**Comment by mgechev** [comment]
[This PR](https://github.com/mgechev/switching-to-angular2/pull/28) should resolve the issue. Would you verify?

**Comment by 404157386** [comment]
It' done for me and looks no problem, thank you so much! 😄

**Comment by jroelens72** [comment]
Works great now. Thanks.
