### ISSUE TITLE
error TS2307/TS2305

### ISSUE THREAD

**Issue by darkbasic** [mgechev/switching-to-angular2#8]
(node:7057) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
app/ch8/ts/todo_webworkers/background_app.ts(1,59): error TS2307: Cannot find module '@angular/platform-worker_app'.
app/ch8/ts/todo_webworkers/background_app.ts(3,9): error TS2305: Module '"/home/niko/devel/switching-to-angular2/node_modules/@angular/core/index"' has no exported member 'platform'.
app/ch8/ts/todo_webworkers/bootstrap.ts(1,9): error TS2305: Module '"/home/niko/devel/switching-to-angular2/node_modules/@angular/core/index"' has no exported member 'platform'.
app/ch8/ts/todo_webworkers/bootstrap.ts(6,8): error TS2307: Cannot find module 'angular2/platform/worker_render'.

This is the output of npm start on Arch Linux (on branch rc).

**Comment by mgechev** [comment]
I see that you've updated to RC. This repository still does not support this version of the framework so we can close this issue.

For updates follow https://github.com/mgechev/switching-to-angular2/pull/7.
