### ISSUE TITLE
symbol-observable.js 404 and other errors

### ISSUE THREAD

**Issue by darkbasic** [mgechev/switching-to-angular2#9]
undefined:1 Uncaught (in promise) TypeError: object is not a constructor(…)
zone.js:101 GET http://localhost:5555/dist/dev/ch4/ts/hello-world/symbol-observable.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM220:3fetchTextFromURL @ system.src.js:1057(anonymous function) @ system.src.js:1561ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1560(anonymous function) @ system.src.js:2451(anonymous function) @ system.src.js:3016(anonymous function) @ system.src.js:3246(anonymous function) @ system.src.js:3805(anonymous function) @ system.src.js:3993(anonymous function) @ system.src.js:4239(anonymous function) @ system.src.js:326ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: e is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: e is not defined(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): ReferenceError: e is not defined(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:101 GET http://localhost:5555/dist/dev/ch4/ts/hello-world/symbol-observable.js 404 (Not Found)

This is from "Chapter 4, Hello world application in TypeScript"
TS examples in rc branch do not work at all in Arch Linux. The ES5 "Hello World" works.

**Comment by mgechev** [comment]
I'm working on migration to Angular RC.1 which should be out by a week or two. Hopefully after that your issues will not be reproducible, otherwise I'll take a look.

**Comment by darkbasic** [comment]
Am I the only one who is surprised by how many things get changed between the beta and the rc?
npm package name changes, deprecations...

**Comment by mgechev** [comment]
Only package names and `*ngFor` variable declaration.

**Comment by darkbasic** [comment]
Good, I only tried a very simple application so far and I already encountered both, so I tought there were much more changes. Thanks.

**Comment by darkbasic** [comment]
Any news on the migration to rc1?

**Comment by mgechev** [comment]
I'm waiting for rc.2 because of the last chapter where we take a look at the WebWorkers support.

**Comment by MAJLGC** [comment]
Are you updating book content too?

**Comment by mgechev** [comment]
Yes, I will. Once the book is updated, in period of few weeks, you can contact Packt for free updates.

**Comment by sonicoder86** [comment]
It is not connected to Angular 2 itself, but rather to the outdated es6-shim package.
https://github.com/blacksonic/angular2-esnext-starter/issues/1
Upgrade it and the error will disappear.

**Comment by mgechev** [comment]
@blacksonic thanks for the comment! :-)
